In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    top_k_accuracy_score,
    confusion_matrix,
    classification_report
)

from xgboost import XGBClassifier

In [5]:
df = pd.read_csv("../data/student_profiles_clean.csv")

In [6]:
career_df = df[df["career_goal"] != "Unknown"].copy()

In [7]:
career_df["ml_signal"] = (
    career_df["python_score"]
    * career_df["machine_learning_score"]
)

career_df["backend_signal"] = (
    career_df["sql_score"]
    * career_df["database_score"]
)

career_df["ai_signal"] = (
    career_df["deep_learning_score"]
    * career_df["statistics_score"]
)

career_df["frontend_signal"] = (
    career_df["html_score"]
    * career_df["css_score"]
)

In [8]:
print(df.shape)

df.info()

df.isnull().sum()

(15000, 45)
<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 45 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   student_id                15000 non-null  str    
 1   age                       15000 non-null  int64  
 2   education_level           15000 non-null  str    
 3   career_goal               15000 non-null  str    
 4   experience_level          15000 non-null  str    
 5   study_hours_per_week      15000 non-null  float64
 6   learning_style            15000 non-null  str    
 7   interest_ai               15000 non-null  float64
 8   interest_data_science     15000 non-null  float64
 9   interest_web_dev          15000 non-null  float64
 10  interest_backend          15000 non-null  float64
 11  interest_frontend         15000 non-null  float64
 12  interest_mobile           15000 non-null  float64
 13  interest_cloud            15000 non-null  float64
 14  inter

student_id                  0
age                         0
education_level             0
career_goal                 0
experience_level            0
study_hours_per_week        0
learning_style              0
interest_ai                 0
interest_data_science       0
interest_web_dev            0
interest_backend            0
interest_frontend           0
interest_mobile             0
interest_cloud              0
interest_cybersecurity      0
python_score                0
cpp_score                   0
java_score                  0
javascript_score            0
html_score                  0
css_score                   0
sql_score                   0
database_score              0
statistics_score            0
probability_score           0
linear_algebra_score        0
calculus_score              0
machine_learning_score      0
deep_learning_score         0
git_score                   0
linux_score                 0
docker_score                0
cloud_score                 0
sessions_c

In [9]:
career_features = [

    "python_score",
    "cpp_score",
    "java_score",
    "javascript_score",

    "html_score",
    "css_score",

    "sql_score",
    "database_score",

    "statistics_score",
    "probability_score",
    "linear_algebra_score",
    "calculus_score",

    "machine_learning_score",
    "deep_learning_score",

    "linux_score",
    "docker_score",
    "cloud_score",

    "interest_ai",
    "interest_data_science",
    "interest_web_dev",
    "interest_backend",
    "interest_frontend",
    "interest_mobile",
    "interest_cloud",
    "interest_cybersecurity",

    "projects_completed",
    "quiz_avg_score",
    "consistency_score",


]

In [10]:

X = career_df[career_features]

y = career_df["career_goal"]

career_encoder = LabelEncoder()
y = career_encoder.fit_transform(y)

In [11]:

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [12]:

xgb = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=1,
    gamma=0.1,
    objective="multi:softprob",   # IMPORTANT
    num_class=len(np.unique(y_train)),
    eval_metric="mlogloss",
    random_state=42
)

xgb.fit(X_train, y_train)

,"objective objective: typing.Union[str, xgboost.sklearn._SklObjWProto, typing.Callable[[typing.Any, typing.Any], typing.Tuple[numpy.ndarray, numpy.ndarray]], NoneType]Specify the learning task and the corresponding learning objective or a customobjective function to be used.For custom objective, see :doc:`/tutorials/custom_metric_obj` and:ref:`custom-obj-metric` for more information, along with the end note forfunction signatures.",'multi:softprob'
,"base_score base_score: typing.Union[float, typing.List[float], NoneType]The initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.Optional[typing.List[xgboost.callback.TrainingCallback]]List of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API <callback_api>`... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: typing.Optional[float]Subsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: typing.Optional[float]Subsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: typing.Optional[float]Subsample ratio of columns when constructing each tree.,0.8
,"device device: typing.Optional[str].. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",None
,"early_stopping_rounds early_stopping_rounds: typing.Optional[int].. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",None
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: typing.Union[str, typing.List[typing.Union[str, typing.Callable]], typing.Callable, NoneType].. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import lo

In [13]:

preds = xgb.predict(X_test)

print(
    "Top-1 Accuracy:",
    accuracy_score(y_test, preds)
)



Top-1 Accuracy: 0.6309278350515464


In [14]:

probs = xgb.predict_proba(X_test)

top3_acc = top_k_accuracy_score(
    y_test,
    probs,
    k=3
)

print(
    "Top-3 Accuracy:",
    top3_acc
)


Top-3 Accuracy: 0.9831615120274914


In [15]:
cm = confusion_matrix(
    y_test,
    preds
)

print(cm)

[[ 14   1   0   0 139   0   0  71   3]
 [  0 141   1   4   1   2 136   0  12]
 [  0   1 103   1   1   0   3   0   5]
 [  0   5   4  71   0   0   2   0  31]
 [ 27   0   0   0 254   0   0 141   9]
 [  0   1   0   3   1 332   3   0  13]
 [  0 136   3   2   1   1 124   1  19]
 [ 23   0   0   0 212   0   1 107   9]
 [  1   8   2   9   7   8   7   3 690]]


In [16]:
print(
    classification_report(
        y_test,
        preds,
        target_names=career_encoder.classes_
    )
)

                        precision    recall  f1-score   support

           AI Engineer       0.22      0.06      0.10       228
     Backend Developer       0.48      0.47      0.48       297
        Cloud Engineer       0.91      0.90      0.91       114
Cybersecurity Engineer       0.79      0.63      0.70       113
        Data Scientist       0.41      0.59      0.49       431
    Frontend Developer       0.97      0.94      0.95       353
  Full Stack Developer       0.45      0.43      0.44       287
           ML Engineer       0.33      0.30      0.32       352
     Software Engineer       0.87      0.94      0.90       735

              accuracy                           0.63      2910
             macro avg       0.60      0.59      0.59      2910
          weighted avg       0.62      0.63      0.62      2910



In [17]:
recall = np.diag(cm) / cm.sum(axis=1)

print("\nPer-Class Recall\n")

for cls, r in zip(
    career_encoder.classes_,
    recall
):
    print(
        f"{cls:25s} {r:.3f}"
    )


Per-Class Recall

AI Engineer               0.061
Backend Developer         0.475
Cloud Engineer            0.904
Cybersecurity Engineer    0.628
Data Scientist            0.589
Frontend Developer        0.941
Full Stack Developer      0.432
ML Engineer               0.304
Software Engineer         0.939


In [18]:
def recommend_careers(
    student_features,
    model,
    encoder,
    top_k=3
):

    probs = model.predict_proba(student_features)

    top_idx = np.argsort(probs[0])[::-1][:top_k]

    recommendations = []

    for idx in top_idx:

        recommendations.append({
            "career": encoder.classes_[idx],
            "confidence": float(
                round(probs[0][idx] * 100, 2)
            )
        })

    return recommendations

In [19]:
student = X_test.iloc[[0]]

recommendations = recommend_careers(
    student,
    xgb,
    career_encoder
)

for rec in recommendations:
    print(rec)

{'career': 'Data Scientist', 'confidence': 50.369998931884766}
{'career': 'ML Engineer', 'confidence': 26.209999084472656}
{'career': 'AI Engineer', 'confidence': 23.1299991607666}


In [20]:
career_requirements = {

    "Data Scientist": {
        "python_score": 80,
        "statistics_score": 85,
        "probability_score": 80,
        "machine_learning_score": 80,
        "projects_completed": 5
    },

    "ML Engineer": {
        "python_score": 85,
        "machine_learning_score": 85,
        "deep_learning_score": 80,
        "linux_score": 70,
        "projects_completed": 5
    },

    "AI Engineer": {
        "python_score": 85,
        "deep_learning_score": 85,
        "statistics_score": 75,
        "machine_learning_score": 80,
        "projects_completed": 5
    },

    "Backend Developer": {
        "python_score": 75,
        "sql_score": 80,
        "database_score": 80,
        "linux_score": 70,
        "docker_score": 70
    },

    "Frontend Developer": {
        "html_score": 85,
        "css_score": 85,
        "javascript_score": 85,
        "projects_completed": 4
    },

    "Full Stack Developer": {
        "html_score": 80,
        "css_score": 80,
        "javascript_score": 80,
        "sql_score": 75,
        "database_score": 75
    },

    "Cloud Engineer": {
        "linux_score": 80,
        "docker_score": 80,
        "cloud_score": 85
    },

    "Cybersecurity Engineer": {
        "linux_score": 75,
        "consistency_score": 75,
        "cloud_score": 60
    },

    "Software Engineer": {
        "python_score": 75,
        "java_score": 70,
        "projects_completed": 4,
        "consistency_score": 70
    }
}

In [21]:
def get_skill_gaps(student_row, career):

    reqs = career_requirements[career]

    gaps = []

    strengths = []

    for skill, target in reqs.items():

        current = float(student_row.iloc[0][skill])

        if current >= target:

            strengths.append(
                (skill, current)
            )

        else:

            gaps.append({
                "skill": skill,
                "current": current,
                "target": target,
                "gap": round(target-current, 1)
            })

    gaps = sorted(
        gaps,
        key=lambda x: x["gap"],
        reverse=True
    )

    return strengths, gaps

In [22]:
career_roadmaps = {

    "Data Scientist": [
        "Master Statistics",
        "Learn Advanced Pandas",
        "Learn Scikit-Learn",
        "Build 3 Data Science Projects",
        "Learn Model Deployment"
    ],

    "ML Engineer": [
        "Master Machine Learning",
        "Learn Deep Learning",
        "Build End-to-End ML Projects",
        "Deploy Models with FastAPI",
        "Learn MLOps"
    ],

    "AI Engineer": [
        "Deep Learning",
        "Computer Vision",
        "NLP",
        "Transformers",
        "Model Deployment"
    ],

    "Backend Developer": [
        "REST APIs",
        "Database Design",
        "Docker",
        "Authentication",
        "Cloud Deployment"
    ],

    "Frontend Developer": [
        "Advanced JavaScript",
        "React",
        "State Management",
        "Frontend Testing",
        "Portfolio Projects"
    ],

    "Full Stack Developer": [
        "React",
        "Node/FastAPI",
        "Databases",
        "Authentication",
        "Deployment"
    ],

    "Cloud Engineer": [
        "Linux",
        "Docker",
        "AWS/Azure/GCP",
        "Kubernetes",
        "CI/CD"
    ],

    "Cybersecurity Engineer": [
        "Networking",
        "Linux Security",
        "Web Security",
        "Penetration Testing",
        "Security Certifications"
    ],

    "Software Engineer": [
        "Data Structures",
        "Algorithms",
        "System Design",
        "Backend Development",
        "Projects"
    ]
}

In [23]:
student = X_test.iloc[[0]]

recommendations = recommend_careers(
    student,
    xgb,
    career_encoder
)

for rank, rec in enumerate(recommendations, start=1):

    print("=" * 50)

    career = rec["career"]

    print(
        f"{rank}. {career}"
    )

    print(
        f"Confidence: {rec['confidence']}%"
    )

    strengths, gaps = get_skill_gaps(
        student,
        career
    )

    print("\nStrengths:")

    for skill, score in strengths:

        print(
            f"✓ {skill}: {score:.1f}"
        )

    print("\nSkill Gaps:")

    for gap in gaps:

        print(
            f"• {gap['skill']} "
            f"(Need +{gap['gap']})"
        )

    print("\nRoadmap:")

    for i, step in enumerate(
        career_roadmaps[career],
        start=1
    ):
        print(
            f"{i}. {step}"
        )

1. Data Scientist
Confidence: 50.369998931884766%

Strengths:

Skill Gaps:
• python_score (Need +55.9)
• statistics_score (Need +37.7)
• machine_learning_score (Need +31.6)
• probability_score (Need +9.4)
• projects_completed (Need +4.0)

Roadmap:
1. Master Statistics
2. Learn Advanced Pandas
3. Learn Scikit-Learn
4. Build 3 Data Science Projects
5. Learn Model Deployment
2. ML Engineer
Confidence: 26.209999084472656%

Strengths:

Skill Gaps:
• python_score (Need +60.9)
• deep_learning_score (Need +40.0)
• linux_score (Need +39.3)
• machine_learning_score (Need +36.6)
• projects_completed (Need +4.0)

Roadmap:
1. Master Machine Learning
2. Learn Deep Learning
3. Build End-to-End ML Projects
4. Deploy Models with FastAPI
5. Learn MLOps
3. AI Engineer
Confidence: 23.1299991607666%

Strengths:

Skill Gaps:
• python_score (Need +60.9)
• deep_learning_score (Need +45.0)
• machine_learning_score (Need +31.6)
• statistics_score (Need +27.7)
• projects_completed (Need +4.0)

Roadmap:
1. Deep L